name: Deploy
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm run render-build
      - run: npm start
      - run: sleep 5 # Give server time to start
      - name: Deploy to Render
        uses: render-io/render-action@v1
        with:
          render_token: ${{ secrets.RENDER_TOKEN }}
          deploy_hook_url: https://api.render.com/deploy/srv-d0ltj315pdvs738mosog?key=Ll4jcmwua6k
          command: deploy